2024-03-20 19:39:49,105 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-20 19:39:49,106 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Configure stats pid to 1096
2024-03-20 19:39:49,106 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Loading settings from /home/souvik/.config/wandb/settings
2024-03-20 19:39:49,106 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Loading settings from /mnt/d/WSL/Flight-Fare-Prediction/wandb/settings
2024-03-20 19:39:49,106 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-20 19:39:49,107 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-20 19:39:49,107 INFO    MainThread:1096 [wandb_init.py:_log_setup():526] Logging user logs to /mnt/d/WSL/Flight-Fare-Prediction/wandb/run-20240320_193949-dataset/logs/debug.log
2024-03-20 19:39:49,108 INFO    MainThread:1096 [wandb_init.py:_log_setup():527] Logging internal logs to /mnt/d/WSL/Flight-Fare-Prediction/wandb/run-20240320_193949-dataset/logs/debug-internal.log
2024-03-20 19:39:49,108 INFO    MainThread:1096 [wandb_init.py:init():566] calling init triggers
2024-03-20 19:39:49,109 INFO    MainThread:1096 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-20 19:39:49,109 INFO    MainThread:1096 [wandb_init.py:init():591] re-initializing run, found existing run on stack: dataset
2024-03-20 19:39:49,112 INFO    MainThread:1096 [wandb_run.py:_finish():1970] finishing run ghsouvikprof/Flight Fare Prediction/dataset
2024-03-20 19:39:49,113 ERROR   MainThread:1096 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-03-20 19:39:49,113 INFO    MainThread:1096 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-20 19:39:49,113 INFO    MainThread:1096 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-20 19:39:49,114 INFO    MainThread:1096 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-20 19:39:49,114 INFO    MainThread:1096 [wandb_run.py:_restore():2193] restore
2024-03-20 19:39:49,115 INFO    MainThread:1096 [wandb_run.py:_restore():2199] restore done
2024-03-20 19:44:24,253 INFO    MainThread:1096 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-20 19:44:24,254 INFO    MainThread:1096 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-20 19:44:24,262 INFO    MainThread:1096 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-03-20 19:44:24,463 INFO    MainThread:1096 [wandb_init.py:init():616] starting backend
2024-03-20 19:44:24,463 INFO    MainThread:1096 [wandb_init.py:init():620] setting up manager
2024-03-20 19:44:24,468 INFO    MainThread:1096 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-20 19:44:24,468 INFO    MainThread:1096 [wandb_init.py:init():628] backend started and connected
2024-03-20 19:44:24,479 INFO    MainThread:1096 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-20 19:44:24,479 INFO    MainThread:1096 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-20 19:44:24,479 INFO    MainThread:1096 [wandb_init.py:init():720] updated telemetry
2024-03-20 19:44:24,526 INFO    MainThread:1096 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-20 19:44:25,899 INFO    MainThread:1096 [wandb_run.py:_on_init():2262] communicating current version
2024-03-20 19:44:25,969 INFO    MainThread:1096 [wandb_run.py:_on_init():2271] got version response upgrade_message: "wandb version 0.16.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-03-20 19:44:25,969 INFO    MainThread:1096 [wandb_init.py:init():804] starting run threads in backend
2024-03-20 19:44:29,719 INFO    MainThread:1096 [wandb_run.py:_console_start():2241] atexit reg
2024-03-20 19:44:29,720 INFO    MainThread:1096 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-20 19:44:29,720 INFO    MainThread:1096 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-20 19:44:29,720 INFO    MainThread:1096 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-20 19:44:29,721 INFO    MainThread:1096 [wandb_init.py:init():847] run started, returning control to user process
2024-03-20 19:53:10,528 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-20 19:53:10,529 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Configure stats pid to 1096
2024-03-20 19:53:10,529 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Loading settings from /home/souvik/.config/wandb/settings
2024-03-20 19:53:10,530 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Loading settings from /mnt/d/WSL/Flight-Fare-Prediction/wandb/settings
2024-03-20 19:53:10,530 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-20 19:53:10,530 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-20 19:53:10,531 INFO    MainThread:1096 [wandb_init.py:_log_setup():526] Logging user logs to /mnt/d/WSL/Flight-Fare-Prediction/wandb/run-20240320_195310-Info/logs/debug.log
2024-03-20 19:53:10,532 INFO    MainThread:1096 [wandb_init.py:_log_setup():527] Logging internal logs to /mnt/d/WSL/Flight-Fare-Prediction/wandb/run-20240320_195310-Info/logs/debug-internal.log
2024-03-20 19:53:10,532 INFO    MainThread:1096 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f1ae01c5950>
2024-03-20 19:53:10,533 INFO    MainThread:1096 [wandb_init.py:init():566] calling init triggers
2024-03-20 19:53:10,533 INFO    MainThread:1096 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-20 19:53:10,534 INFO    MainThread:1096 [wandb_init.py:init():591] re-initializing run, found existing run on stack: dataset
2024-03-20 19:53:10,542 INFO    MainThread:1096 [wandb_run.py:_finish():1970] finishing run ghsouvikprof/Flight Fare Prediction/dataset
2024-03-20 19:53:10,542 INFO    MainThread:1096 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-20 19:53:10,543 INFO    MainThread:1096 [wandb_run.py:_restore():2193] restore
2024-03-20 19:53:10,544 INFO    MainThread:1096 [wandb_run.py:_restore():2199] restore done
