2024-03-20 20:32:08,353 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-20 20:32:08,356 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Configure stats pid to 1096
2024-03-20 20:32:08,358 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Loading settings from /home/souvik/.config/wandb/settings
2024-03-20 20:32:08,361 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Loading settings from /mnt/d/WSL/Flight-Fare-Prediction/wandb/settings
2024-03-20 20:32:08,364 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-20 20:32:08,368 INFO    MainThread:1096 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-20 20:32:08,373 INFO    MainThread:1096 [wandb_init.py:_log_setup():526] Logging user logs to /mnt/d/WSL/Flight-Fare-Prediction/wandb/run-20240320_203208-m9m62ttu/logs/debug.log
2024-03-20 20:32:08,376 INFO    MainThread:1096 [wandb_init.py:_log_setup():527] Logging internal logs to /mnt/d/WSL/Flight-Fare-Prediction/wandb/run-20240320_203208-m9m62ttu/logs/debug-internal.log
2024-03-20 20:32:08,380 INFO    MainThread:1096 [wandb_init.py:init():566] calling init triggers
2024-03-20 20:32:08,384 INFO    MainThread:1096 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-20 20:32:08,387 INFO    MainThread:1096 [wandb_init.py:init():616] starting backend
2024-03-20 20:32:08,390 INFO    MainThread:1096 [wandb_init.py:init():620] setting up manager
2024-03-20 20:32:08,403 INFO    MainThread:1096 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-20 20:32:08,407 INFO    MainThread:1096 [wandb_init.py:init():628] backend started and connected
2024-03-20 20:32:08,429 INFO    MainThread:1096 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-20 20:32:08,432 INFO    MainThread:1096 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-20 20:32:08,435 INFO    MainThread:1096 [wandb_init.py:init():720] updated telemetry
2024-03-20 20:32:08,586 INFO    MainThread:1096 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-20 20:33:38,625 ERROR   MainThread:1096 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-20 20:33:38,760 ERROR   MainThread:1096 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/souvik/miniconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/souvik/miniconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
